# Generated by Django 4.2.11 on 2024-11-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_merge_20241109_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='discount_value',
        ),
    ]
